#ifndef _REDIS_KEYS_H_
#define _REDIS_KEYS_H_

#define REDIS_SERVER_IP "127.0.0.1"
#define REDIS_SERVER_PORT "6379"

#define FILE_PUBLIC_ZSET "FILE_PUBLIC_ZSET"

#define FILE_NAME_HASH "FILE_NAME_HASH"

#endif
